# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "travis" do |travis|
    # Base image
    travis.vm.box = "generic/ubuntu2004"

    # Network with host
    travis.vm.network "private_network", ip: "192.168.33.12"

    # VirtualBox
    travis.vm.provider "virtualbox" do |vb|
      # Customize the spec
      vb.memory = "8192"
      vb.cpus = "4"
    end

    # Provision
    config.vm.provision "shell", path: "provision.sh", privileged: false
  end

end
