---
  - name: EOEPCA local development environment
    hosts: all
    become: yes

    roles:
    - geerlingguy.git
    - reallyenglish.git
    - mongrelion.docker
    - andrewrothstein.jq
    - gantsign.kubernetes

    vars:  
      docker_version: "18.06"  
      docker_config:
        live-restore: true
        userland-proxy: false  
      kubernetes_node_type: admin
      git_additional_packages:
        - "{% if ansible_os_family == 'FreeBSD' %}gitflow{% elif ansible_os_family == 'OpenBSD' %}git-cvs{% elif ansible_os_family == 'RedHat' %}git-cvs{% else %}git-flow{% endif %}"
  